version: '3'

services:
  db:
    image: mariadb:10.5
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: db-name
      MYSQL_USER: username
      MYSQL_PASSWORD: userpw
    networks:
      - yournetwork

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    expose:
      - 80
    volumes:
      - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: username
      WORDPRESS_DB_PASSWORD: userpw
      WORDPRESS_DB_NAME: db-name
    networks:
      yournetwork:
        ipv4_address: 172.18.0.3

volumes:
  db_data:

networks:
  local:
    external: true
